#!/bin/sh
set -e

case "$1" in
    remove|deconfigure|upgrade)
        if [ -d /run/systemd/system ]; then
            systemctl stop sloth >/dev/null 2>&1 || true
        fi
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
